name: ci

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - 'README.md'
      - 'Privacy Policy.md'
      - '.github'
      - 'LICENSE'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d')"
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: | 
            ${{ secrets.DOCKER_HUB_USERNAME }}/dont-be-like-this:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/dont-be-like-this:${{ steps.date.outputs.date }}
